# 网站基本信息
lang: en-US
timezone: Asia/Shanghai

title: Die Casting Expert
tagline: Aluminum, Magnesium, Semi-Solid Casting & CNC Machining Solutions

# 你的个人或公司信息
author:
  name: Hank
  twitter_username: 
  email: hank@yourdomain.com # 请替换为你的邮箱
  uri: https://yourdomain.com # 你的公司网站地址

# 站点链接
url: https://diecasting.github.io
baseurl: ""

# 版权设置
copyright:
  name: Hank
  since: 2026

# Google Analytics (如果有，建议在此添加)
google_analytics:
  id: G-XXXXXXXXXX
